### ISSUE TITLE
TestBug

### ISSUE THREAD

**Issue by AdrianoFSilva1** [SimonCropp/EfCore.InMemoryHelpers#47]
![imagem](https://user-images.githubusercontent.com/47454837/52487609-e86c5700-2bb5-11e9-8d99-f86d72ffeabd.png)
![imagem](https://user-images.githubusercontent.com/47454837/52487623-f02bfb80-2bb5-11e9-8269-d49874a77981.png)
![imagem](https://user-images.githubusercontent.com/47454837/52487638-f621dc80-2bb5-11e9-85a1-dc1ae41e306d.png)
![imagem](https://user-images.githubusercontent.com/47454837/52487653-ffab4480-2bb5-11e9-8cf8-16f5fabbd46f.png)
What am i doing wrong? The result of the tests is completly random.

**Comment by SimonCropp** [comment]
Please read the issue template https://github.com/SimonCropp/EfCore.InMemoryHelpers/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by SimonCropp** [comment]
closed due to no response
