### ISSUE TITLE
ConcurrencyValueFinder assumes that any property with IsConcurrencyToken set is a row version

### ISSUE THREAD

**Issue by blushingpenguin** [SimonCropp/EfCore.InMemoryHelpers#7]
```
var concurrencyProperty = entityType.GetProperties()
    .SingleOrDefault(x => x.IsConcurrencyToken);
```

however it's possible to have a concurrency token that isn't a row version, and also that doesn't necessarily take an autogenerated value.  A specific example of this is from ASP.NET identity (which is where I ran into this issue):

```
public class IdentityUser<TKey, TUserLogin, TUserRole, TUserClaim>
    : Microsoft.AspNet.Identity.EntityFramework.IdentityUser<TKey, TUserLogin, TUserRole, TUserClaim>
{
...
    /// <summary>
    ///     Concurrency stamp
    /// </summary>
    public virtual string ConcurrencyStamp { get; set; } = Guid.NewGuid().ToString();
}
...
modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b => {
    b.Property<string>("ConcurrencyStamp")
        .IsConcurrencyToken();
```

I have worked around this issue by adding `&& x.ValueGenerated == ValueGenerated.OnAddOrUpdate` to the test in ConcurrencyValueFinder.GetConcurrency (IsRowVersion() in the model builder also sets this property).

However it seems that there is an additional assumption that the underlying data is stored as a byte[] array -- I'm not sure if that needs addressing too as in the example above the concurrency token is a string.

**Comment by SimonCropp** [comment]
@mdw211 could you submit a PR with a failing test that represents your scenario?

**Comment by blushingpenguin** [comment]
[PR](https://github.com/SimonCropp/EfCore.InMemoryHelpers/pull/8) as requested
